### ISSUE TITLE
Games missing in Depressurizer

### ISSUE THREAD

**Issue by richardfrost** [Depressurizer/Depressurizer#17]
## Expected Behavior
All games/software being listed

## Actual Behavior
I just cleared out all profiles/data etc and started with version 1.3.0, and have several hundred games not visible to Depressurizer anymore. When I saved the categorization to steam it moved those games from their categories into the generic "Games" category. An example of a game that is no longer showing up in Depressurizer is `Bioshock Infinite`. I can get a bigger list if that might be helpful.

## Steps to Reproduce the Problem
1. Cleaned all files in %Appdata%\Depressurizer and the Depressurizer directory.
2. Load profile and initialize data
3. Search in the app for a game like "Bioshock Infinite" and its not there. I just dusted off version 1.1.2 and all my games show up in that one as expected. (Not sure if it is related to #11 or not, but this is definitely a much bigger problem for me than the other one was ;) )

Thanks for all your hard work on the project!

## Specifications
  - Version: 1.3.0
  - Operating System: Windows 10

**Comment by mvegter** [comment]
Should be fixed with the [latest release](https://github.com/mvegter/Depressurizer/releases/tag/v1.4.0).

**Comment by richardfrost** [comment]
Thanks for getting to that so fast!

I'm not sure what I'm doing wrong, but here is a couple examples of what I'm seeing with `1.4.0` vs `1.1.2`. This was with fresh `%AppData%\Depressurizer` folders. I am not sure why there are discrepancies, but I can give more details if needed/wanted.

## Counts
**1.1.2**
![image](https://user-images.githubusercontent.com/1507205/34973836-10375d94-fa47-11e7-9651-20a3cc0cb4c1.png)


**1.4.0**
![image](https://user-images.githubusercontent.com/1507205/34973434-c3468520-fa44-11e7-9e22-cd3065612a6b.png)


## Tidalis
**1.1.2**
![image](https://user-images.githubusercontent.com/1507205/34972856-829817d0-fa41-11e7-8b35-daca396030c1.png)

**1.4.0**
![image](https://user-images.githubusercontent.com/1507205/34972859-880b5592-fa41-11e7-8eb5-9bc7f1b5cd0f.png)


## Prey
**1.1.2**
![image](https://user-images.githubusercontent.com/1507205/34973920-79920000-fa47-11e7-9777-281c5d7850ed.png)

**1.4.0**
![image](https://user-images.githubusercontent.com/1507205/34973913-6f7d61ae-fa47-11e7-8705-d54da060e802.png)


## Bioshock
**1.1.2**
![image](https://user-images.githubusercontent.com/1507205/34973940-917f1a22-fa47-11e7-9166-28d357ebd901.png)

**1.4.0**
![image](https://user-images.githubusercontent.com/1507205/34973960-b1ce0932-fa47-11e7-966a-7d76524269ae.png)

Notes: I have Depressurizer `1.1.2` on one computer, and Depressurizer `1.4.0` on another computer. Both are Windows 10, fully updated. Both use my same Microsoft and Steam accounts, and should be comparable for these tests. If that assumption is wrong I apologize.

Sorry to keep coming up with issues, I know how hard it is to maintain a project. Thanks for all your work!

**Comment by freggern** [comment]
Hey you can try my quickfix https://www.dropbox.com/s/uh69njlo42iav3g/Depressurizer%20Debug%20-%20Quickfix.zip?dl=0 . Its include a fix that most games have now the correct LastScraped und LastAppInfo time info. For my problem #19 .

That games are not shown correct in game list i see by my testing when I abort the scrabing when I start the app the first time... Think the problem is that then the database entries are not set in the database...

**Comment by richardfrost** [comment]
Sorry that took me a bit, but I have cleared out the db and appdata and fired up the version you linked above. It seems to be about the same as before.

1 prey is listed (instead of 2. The first is unlisted on the steam store, which probably has something to do with it.),Tidalis still doesn't show up. And for Bioshock, only the remastered ones are shown.

Not sure if there was anything else you wanted me to test, but I can. Thanks again for all your work on this project!

**Comment by turbana** [comment]
I'm also having this issue where some games are categorized under Games in steam and either don't show up on Depressurizer or are incorrectly listed. I've tried under both 1.4.0 and the quickfix listed above. I've deleted both the db.json and the entire appdata folder under both versions.

(1) I own the following: Darksiders, Darksiders Warmastered Edition, and Darksiders II. Only the Warmastered edition shows up in Depressurizer. I can list more if it would be helpful.

(2) I also notice some games are incorrectly identified as demos. Toki Tori is one such game. It has categories assigned to it in Depressurizer, but shows up under Games in steam. Toki Tori 2+ is seen correctly.

**Comment by mvegter** [comment]
@turbana @richardfrost Fixed in v2.0.0 [Download Here](https://github.com/mvegter/Depressurizer/releases/tag/v2.0.0)

**Comment by richardfrost** [comment]
I just checked, and it looks good! I am seeing all the titles that weren't showing up before. Thanks for all your hard work!

**Comment by turbana** [comment]
Fixed for me as well. Thanks!
