### ISSUE TITLE
Scraping not successful on all games

### ISSUE THREAD

**Issue by Qubits01** [Depressurizer/Depressurizer#68]
**Describe the bug**
I scraped through all my games multiple times. All are marked as scraped in database editor.
However, for around 10% of my games, it didn't download any data. Some are removed from store, but most are still there.
When I go to the database manager and filter for a specific game and only scrape that single one, the data download is successful.

**To Reproduce**
1. Scrape all games
2. find a game that's in the store but shows Year:unknown and no other data
3. Goto Database Editor, filter for that game and scrape it
4. Game now shows all data in the list view

**Expected behavior**
Get all data with mass scraping

**Screenshots**
All games were scraped multiple times, all at once. Example: Abalone is missing data.
![dep1](https://user-images.githubusercontent.com/39989491/45925612-0e20f880-bf54-11e8-80a2-6d6b9483535c.png)
Database Editor shows all games (alos Abalone) as scraped.
![dep2](https://user-images.githubusercontent.com/39989491/45925613-0e20f880-bf54-11e8-8c7f-0d0ceacb0dc5.png)
I filter the game and scrape it as the only one
![dep3](https://user-images.githubusercontent.com/39989491/45925614-0e20f880-bf54-11e8-9b78-7152812ceb95.png)
the information appears
![dep4](https://user-images.githubusercontent.com/39989491/45925615-0eb98f00-bf54-11e8-9528-c148bf9d11c7.png)

**Desktop (please complete the following information):**
 - OS: Win7
 - Depressurizer: 3.1.0

**Additional context**
What would help me: Add an option in main view that when you select a game you can do scraping with context menu

**Comment by mvegter** [comment]
@Qubits01 I'm not sure what the issue is, after scraping `Abalone` myself I got the following results:
![image](https://user-images.githubusercontent.com/25134477/45926276-4bb85e00-bf21-11e8-8153-2ae780f2950b.png)

**Comment by Qubits01** [comment]
As I described above, that works for me too if I scrape it by itself.
It seems to be an issue when I do mass scraping of all my 7000+ games.
As I wrote above, around 10% of the game won't get their data downloaded.

Explain why the data for abalone doesn't show for me even though it's marked scraped.
Abalone is just an example of many..

I can't work around this problem because there doesn't seem to be an option where I could easily scrape only the ~500 games that are missing info.

**Comment by mvegter** [comment]
@Qubits01 Thanks for clarifying, going to look into it.

**Comment by graphixillusion** [comment]
How to change the scrape server?

**Comment by TheKojukinator** [comment]
I noticed the new release doesn't come with a DB, so it gets generated on first run. Well my DB is missing ALL game info. Scraping fails on every game, the only data that pulls in is HLTB.

![image](https://user-images.githubusercontent.com/30471780/46320619-39879100-c5ad-11e8-8bb7-0a583ab9ab69.png)

Attaching my GameDB and redacted log in case it helps...

[Depressurizer_redacted.log](https://github.com/Depressurizer/Depressurizer/files/2435975/Depressurizer_redacted.log)
[GameDB.xml.gz](https://github.com/Depressurizer/Depressurizer/files/2435976/GameDB.xml.gz)

**Comment by Qubits01** [comment]
This it what it looks like at my end:

A scraped game from mass scraping all games
![pres1](https://user-images.githubusercontent.com/39989491/46330590-9d15cb00-c64e-11e8-88ac-0e353023d912.png)

The same game after (re-)scraping individually
![pres2](https://user-images.githubusercontent.com/39989491/46330591-9d15cb00-c64e-11e8-9b6b-2d97823fb12a.png)

**Comment by sukhmel** [comment]
I have a same problem where nothing gets scraped in version 4.0 and part of games are scraped successfully at version 3.1

**Comment by Qubits01** [comment]
sorry, I didn't realize v4 has been released meanwhile.
All my reporting is about v3.1
From what I read it seems like v4 made it even worse unfortunately.

**Comment by mvegter** [comment]
@all, this has to do with the repository transfer to the Depressurizer organization page. Currently working on fix everything.

**Comment by Parsnip** [comment]
General scarping seems to work again in 4.1.0.
But I'm not getting HLTB entries for everything, for example Banished has a HLTB page but I can't get Depressurizer to fetch the times for it.

**Comment by Qubits01** [comment]
Well I have big trouble with 4.1.
But it seems not everyone has.

At startup I get this screen:
![41a](https://user-images.githubusercontent.com/39989491/46544380-61089180-c8fe-11e8-8d32-3c084d8f72d4.png)

After autoscrape of all games, no game info at all is downloaded. Scraping of single files also doesn't work for me.
![41b](https://user-images.githubusercontent.com/39989491/46544381-61089180-c8fe-11e8-84fd-829036c90d3f.png)

Any ideas?

**Comment by joridiculous** [comment]
Similar issues here (ver.4.0)
Half'ish of the games doesn't get any data 'scraped'. Going to DB editor and manually scrape does nothing.
![screenshot 1413](https://user-images.githubusercontent.com/25628732/46620922-6516f800-cb26-11e8-8a8a-8f7e607b02c8.png)
(Also tried v.4.1 but ditched it immediately. It didn't read *any* data, didn't find my profile and reset the the DB.

**Comment by Qubits01** [comment]
I fixed my problem.
Windows 7 does not support TLS by default. It needs to be activated via the registry.
[https://support.microsoft.com/en-us/help/3140245/update-to-enable-tls-1-1-and-tls-1-2-as-a-default-secure-protocols-in](url)
So maybe it should be noted in the readme that Depressurizer does not support Win7 out of the box.

**Comment by mashpl** [comment]
I just wanted to add that I have exactly same symptoms as Qubits01 with 4.1.0 (freshly installed, never used Depressurizer before, same SSL/TLS message at the start and failing to scrape any data apart from HLBT and platforms) and also on Windows 7 (64bit, SP1) but the fix above didn't do it for me. Checked the registry for the two new entries and they are there with seemingly correct values. Still error message and still empty details for games in the database after scraping (doesn't matter if the whole or just my 400-ish games)

**Comment by mashpl** [comment]
FYI the 4.2.0 released fixed scraping of reviews. Now only genres, tags, flags and release dates are missing. Also the database correctly detected 100 more games that I own, seems like the list is complete now.

edit: actually A LOT of reviews are still missing. Out of 450 games only 133 fetched their reviews. I'd expect 350+ successful fetches.

**Comment by Parsnip** [comment]
HLTB fetch is still a bit unreliable as well. It just doesn't find times for some games even though there is a page for them. For example Hand of Fate. No idea why deprez doesn't find the times for it.

https://store.steampowered.com/app/266510/Hand_of_Fate/
https://howlongtobeat.com/game.php?id=20740

**Comment by Qubits01** [comment]
> Now only genres, tags, flags and release dates are missing.

Strange, this info has >90% complete rate now with version 4.2
 
> edit: actually A LOT of reviews are still missing. 

Yes! Only ~6% of my games show review score and Number of review. Please fix!

**Comment by kazerniel** [comment]
Thanks @Qubits01 , it fixed the error message and the scraping :)

**Comment by mvegter** [comment]
If this is still present in the latest release, please feel free to create a new issue with up-to-date information.
